# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uploads/uploads_events.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from common import common_types_pb2 as common_dot_common__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='uploads/uploads_events.proto',
  package='killrvideo.uploads.events',
  syntax='proto3',
  serialized_options=_b('\252\002\031KillrVideo.Uploads.Events'),
  serialized_pb=_b('\n\x1cuploads/uploads_events.proto\x12\x19killrvideo.uploads.events\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19\x63ommon/common_types.proto\"y\n\x1dUploadedVideoProcessingFailed\x12)\n\x08video_id\x18\x01 \x01(\x0b\x32\x17.killrvideo.common.Uuid\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"z\n\x1eUploadedVideoProcessingStarted\x12)\n\x08video_id\x18\x01 \x01(\x0b\x32\x17.killrvideo.common.Uuid\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"|\n UploadedVideoProcessingSucceeded\x12)\n\x08video_id\x18\x01 \x01(\x0b\x32\x17.killrvideo.common.Uuid\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x9c\x01\n\x16UploadedVideoPublished\x12)\n\x08video_id\x18\x01 \x01(\x0b\x32\x17.killrvideo.common.Uuid\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tvideo_url\x18\x03 \x01(\t\x12\x15\n\rthumbnail_url\x18\x04 \x01(\tB\x1c\xaa\x02\x19KillrVideo.Uploads.Eventsb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,common_dot_common__types__pb2.DESCRIPTOR,])




_UPLOADEDVIDEOPROCESSINGFAILED = _descriptor.Descriptor(
  name='UploadedVideoProcessingFailed',
  full_name='killrvideo.uploads.events.UploadedVideoProcessingFailed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='video_id', full_name='killrvideo.uploads.events.UploadedVideoProcessingFailed.video_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='killrvideo.uploads.events.UploadedVideoProcessingFailed.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=240,
)


_UPLOADEDVIDEOPROCESSINGSTARTED = _descriptor.Descriptor(
  name='UploadedVideoProcessingStarted',
  full_name='killrvideo.uploads.events.UploadedVideoProcessingStarted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='video_id', full_name='killrvideo.uploads.events.UploadedVideoProcessingStarted.video_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='killrvideo.uploads.events.UploadedVideoProcessingStarted.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=364,
)


_UPLOADEDVIDEOPROCESSINGSUCCEEDED = _descriptor.Descriptor(
  name='UploadedVideoProcessingSucceeded',
  full_name='killrvideo.uploads.events.UploadedVideoProcessingSucceeded',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='video_id', full_name='killrvideo.uploads.events.UploadedVideoProcessingSucceeded.video_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='killrvideo.uploads.events.UploadedVideoProcessingSucceeded.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=490,
)


_UPLOADEDVIDEOPUBLISHED = _descriptor.Descriptor(
  name='UploadedVideoPublished',
  full_name='killrvideo.uploads.events.UploadedVideoPublished',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='video_id', full_name='killrvideo.uploads.events.UploadedVideoPublished.video_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='killrvideo.uploads.events.UploadedVideoPublished.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_url', full_name='killrvideo.uploads.events.UploadedVideoPublished.video_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thumbnail_url', full_name='killrvideo.uploads.events.UploadedVideoPublished.thumbnail_url', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=649,
)

_UPLOADEDVIDEOPROCESSINGFAILED.fields_by_name['video_id'].message_type = common_dot_common__types__pb2._UUID
_UPLOADEDVIDEOPROCESSINGFAILED.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_UPLOADEDVIDEOPROCESSINGSTARTED.fields_by_name['video_id'].message_type = common_dot_common__types__pb2._UUID
_UPLOADEDVIDEOPROCESSINGSTARTED.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_UPLOADEDVIDEOPROCESSINGSUCCEEDED.fields_by_name['video_id'].message_type = common_dot_common__types__pb2._UUID
_UPLOADEDVIDEOPROCESSINGSUCCEEDED.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_UPLOADEDVIDEOPUBLISHED.fields_by_name['video_id'].message_type = common_dot_common__types__pb2._UUID
_UPLOADEDVIDEOPUBLISHED.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['UploadedVideoProcessingFailed'] = _UPLOADEDVIDEOPROCESSINGFAILED
DESCRIPTOR.message_types_by_name['UploadedVideoProcessingStarted'] = _UPLOADEDVIDEOPROCESSINGSTARTED
DESCRIPTOR.message_types_by_name['UploadedVideoProcessingSucceeded'] = _UPLOADEDVIDEOPROCESSINGSUCCEEDED
DESCRIPTOR.message_types_by_name['UploadedVideoPublished'] = _UPLOADEDVIDEOPUBLISHED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UploadedVideoProcessingFailed = _reflection.GeneratedProtocolMessageType('UploadedVideoProcessingFailed', (_message.Message,), dict(
  DESCRIPTOR = _UPLOADEDVIDEOPROCESSINGFAILED,
  __module__ = 'uploads.uploads_events_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.uploads.events.UploadedVideoProcessingFailed)
  ))
_sym_db.RegisterMessage(UploadedVideoProcessingFailed)

UploadedVideoProcessingStarted = _reflection.GeneratedProtocolMessageType('UploadedVideoProcessingStarted', (_message.Message,), dict(
  DESCRIPTOR = _UPLOADEDVIDEOPROCESSINGSTARTED,
  __module__ = 'uploads.uploads_events_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.uploads.events.UploadedVideoProcessingStarted)
  ))
_sym_db.RegisterMessage(UploadedVideoProcessingStarted)

UploadedVideoProcessingSucceeded = _reflection.GeneratedProtocolMessageType('UploadedVideoProcessingSucceeded', (_message.Message,), dict(
  DESCRIPTOR = _UPLOADEDVIDEOPROCESSINGSUCCEEDED,
  __module__ = 'uploads.uploads_events_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.uploads.events.UploadedVideoProcessingSucceeded)
  ))
_sym_db.RegisterMessage(UploadedVideoProcessingSucceeded)

UploadedVideoPublished = _reflection.GeneratedProtocolMessageType('UploadedVideoPublished', (_message.Message,), dict(
  DESCRIPTOR = _UPLOADEDVIDEOPUBLISHED,
  __module__ = 'uploads.uploads_events_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.uploads.events.UploadedVideoPublished)
  ))
_sym_db.RegisterMessage(UploadedVideoPublished)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
