dist: xenial # required for Python >= 3.7
language: python
python:
- "3.7"

# Build the docker image
script:
- ./scripts/docker-build.sh

# If successful, see if we need to publish also
after_success:
- ./scripts/travis-publish.sh

# Sudo required for doing docker build
sudo: required
services:
- docker

env:
  global:
  # DOCKER_USER
    secure: "MG7FSxStuA5V00Vej3kJBcLg2XTeJLn6oPb/V1ZCcOd5769UnCqBqwpshsfcDAxBnklMl1tVJrwlm7eG8Yf2+HHJTXWSX+rNh4KLZm7C0YB2LzJoPEWHSArD6t4h+LtjFm6gjTFNfLwB2eaiaqimNvDNr+X7rXxf1Lt5/Si0pMNDsyPHHkCNbpi9bHL5WpNPdNyv13V/IJVXNH74nTdJhMW7ayQnuZ/IWkr8mtSHmofoHBN+UiGSllQVzUOP6clEHXam/YZxrvDwiF5RmQfKoyCDx30CEiJBQWBAIcJe2P+AC6Uk7IKRt+67MWpBSQjBoVyaqc4xn2kwQ/doEQsS9MlTaEKFds8jGIjDRGRl6wM08dzsCMGDD5slVqnhkEjeyRuwrF31rd3Lit5cuGUn5XDiOXJ/DnisOFiJp59Vm8K4a2lEHoTuJQp8i28E6wWEOWSwejbOdPApAVXuxrWtuVbw9hcIgnfTvD2pzVLruSXA3evBlfnj4Y8FOYYVkinpbklbI/F8kSfeeKR7lKnjv8MFMNYqYgeTZsy7ICDbo9wB3sZXPCzTuReek73E9Dl2DXgBceMtBNThumvQvIAnqgcJ/KHLS0xAcrWCnhMzNLSgKSEbfmQ83VNCQm9/c0aqP12yvLNchMvoePbx+2REM0IkaOJBiiIvLGwBOmElUuo="
  # DOCKER_PASS
    secure: "F8sNKMia3lYxc7X+vn7448CxX3z0Df06RJPBChM7oAREP2fxvOEzgipgMbHPx4POcdSr60aDSJfDfXpTPRylFkkNK8d733HQdvsLA1lyVoHr6pKRjU8QNz4AMMIxHNhunMTQ5XfJEn9Q+a5qmcsho9HOCA4rfhT/thKIC9QlX/qNme4v27n0vjvqh7cUHU2gV5ykZHf324WBRrzHgYyEe0ieNJ6Tvmxf+Kzm3JB6X20uqst48tS/pPDAkdQPnlu4kWprFwRfKboSjLQjgnnHY+zZLvgvP7kyfO817M5n7iH5WAD1jK4o1stb0tSM/1u4SwssxIyLOKJeclCfY9XkG3DjtNuU+43MUKsI8Q/39fzqW39nxYUCcM4kbW5rWZUCz9PfCs3MOd4xhgX7+mf9xT66HclsJcdbqyrty41rSB0/x8T2LtzoW/Q6UD2GNHimkRu2cTDI2aV1HxbZjqGlFxK5x77CPQAuFxtbnaUH6pSoi3fiYyJiivLLTGzeisA2qpjeSMS2+q3KZIpcqaDIMV4slvfng7gurm2TvtlEtwG1ITJ01dokcXNy+vcw/3go606Aemr/bK2Aot00X0/HDQaX1/v0rJVWXW/c3Gcso6Jzmi1C9vp8gTOr5closfqZFyDJFC1Wuv+vdAzW4MMuwAuc4DnoiwQ6Gm8LamV9oy8="
