version: '3'
services:
  backend:
    image: killrvideo-python-local
    depends_on:
      - dse
  
  dse: 
    image: datastax/dse-server:6.7.4
    command: [ -s -g ]
    environment:
      DS_LICENSE: accept
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1

  dse-config: 
    image: killrvideo/killrvideo-dse-config:3.0.0
    depends_on:
      - dse
  
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  # Start a Kafka Broker for Killrvideo
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic-kv-videoCreation:1:1,topic-kv-userCreation:1:1,topic-kv-videoRating:1:1,topic-kv-commentCreation:1:1"
    ports:
      - 9092:9092
