# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comments/comments_events.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from common import common_types_pb2 as common_dot_common__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='comments/comments_events.proto',
  package='killrvideo.comments.events',
  syntax='proto3',
  serialized_options=_b('\252\002\032KillrVideo.Comments.Events'),
  serialized_pb=_b('\n\x1e\x63omments/comments_events.proto\x12\x1akillrvideo.comments.events\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19\x63ommon/common_types.proto\"\xd3\x01\n\x14UserCommentedOnVideo\x12(\n\x07user_id\x18\x01 \x01(\x0b\x32\x17.killrvideo.common.Uuid\x12)\n\x08video_id\x18\x02 \x01(\x0b\x32\x17.killrvideo.common.Uuid\x12/\n\ncomment_id\x18\x03 \x01(\x0b\x32\x1b.killrvideo.common.TimeUuid\x12\x35\n\x11\x63omment_timestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x1d\xaa\x02\x1aKillrVideo.Comments.Eventsb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,common_dot_common__types__pb2.DESCRIPTOR,])




_USERCOMMENTEDONVIDEO = _descriptor.Descriptor(
  name='UserCommentedOnVideo',
  full_name='killrvideo.comments.events.UserCommentedOnVideo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='killrvideo.comments.events.UserCommentedOnVideo.user_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_id', full_name='killrvideo.comments.events.UserCommentedOnVideo.video_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comment_id', full_name='killrvideo.comments.events.UserCommentedOnVideo.comment_id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comment_timestamp', full_name='killrvideo.comments.events.UserCommentedOnVideo.comment_timestamp', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=334,
)

_USERCOMMENTEDONVIDEO.fields_by_name['user_id'].message_type = common_dot_common__types__pb2._UUID
_USERCOMMENTEDONVIDEO.fields_by_name['video_id'].message_type = common_dot_common__types__pb2._UUID
_USERCOMMENTEDONVIDEO.fields_by_name['comment_id'].message_type = common_dot_common__types__pb2._TIMEUUID
_USERCOMMENTEDONVIDEO.fields_by_name['comment_timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['UserCommentedOnVideo'] = _USERCOMMENTEDONVIDEO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserCommentedOnVideo = _reflection.GeneratedProtocolMessageType('UserCommentedOnVideo', (_message.Message,), dict(
  DESCRIPTOR = _USERCOMMENTEDONVIDEO,
  __module__ = 'comments.comments_events_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.comments.events.UserCommentedOnVideo)
  ))
_sym_db.RegisterMessage(UserCommentedOnVideo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
