# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from video_catalog import video_catalog_service_pb2 as video__catalog_dot_video__catalog__service__pb2


class VideoCatalogServiceStub(object):
  """Service responsible for tracking the catalog of available videos for playback
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SubmitUploadedVideo = channel.unary_unary(
        '/killrvideo.video_catalog.VideoCatalogService/SubmitUploadedVideo',
        request_serializer=video__catalog_dot_video__catalog__service__pb2.SubmitUploadedVideoRequest.SerializeToString,
        response_deserializer=video__catalog_dot_video__catalog__service__pb2.SubmitUploadedVideoResponse.FromString,
        )
    self.SubmitYouTubeVideo = channel.unary_unary(
        '/killrvideo.video_catalog.VideoCatalogService/SubmitYouTubeVideo',
        request_serializer=video__catalog_dot_video__catalog__service__pb2.SubmitYouTubeVideoRequest.SerializeToString,
        response_deserializer=video__catalog_dot_video__catalog__service__pb2.SubmitYouTubeVideoResponse.FromString,
        )
    self.GetVideo = channel.unary_unary(
        '/killrvideo.video_catalog.VideoCatalogService/GetVideo',
        request_serializer=video__catalog_dot_video__catalog__service__pb2.GetVideoRequest.SerializeToString,
        response_deserializer=video__catalog_dot_video__catalog__service__pb2.GetVideoResponse.FromString,
        )
    self.GetVideoPreviews = channel.unary_unary(
        '/killrvideo.video_catalog.VideoCatalogService/GetVideoPreviews',
        request_serializer=video__catalog_dot_video__catalog__service__pb2.GetVideoPreviewsRequest.SerializeToString,
        response_deserializer=video__catalog_dot_video__catalog__service__pb2.GetVideoPreviewsResponse.FromString,
        )
    self.GetLatestVideoPreviews = channel.unary_unary(
        '/killrvideo.video_catalog.VideoCatalogService/GetLatestVideoPreviews',
        request_serializer=video__catalog_dot_video__catalog__service__pb2.GetLatestVideoPreviewsRequest.SerializeToString,
        response_deserializer=video__catalog_dot_video__catalog__service__pb2.GetLatestVideoPreviewsResponse.FromString,
        )
    self.GetUserVideoPreviews = channel.unary_unary(
        '/killrvideo.video_catalog.VideoCatalogService/GetUserVideoPreviews',
        request_serializer=video__catalog_dot_video__catalog__service__pb2.GetUserVideoPreviewsRequest.SerializeToString,
        response_deserializer=video__catalog_dot_video__catalog__service__pb2.GetUserVideoPreviewsResponse.FromString,
        )


class VideoCatalogServiceServicer(object):
  """Service responsible for tracking the catalog of available videos for playback
  """

  def SubmitUploadedVideo(self, request, context):
    """Submit an uploaded video to the catalog
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubmitYouTubeVideo(self, request, context):
    """Submit a YouTube video to the catalog
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetVideo(self, request, context):
    """Gets a video from the catalog
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetVideoPreviews(self, request, context):
    """Gets video previews for a limited number of videos from the catalog
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLatestVideoPreviews(self, request, context):
    """Gets video previews for the latest (i.e. newest) videos from the catalog
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserVideoPreviews(self, request, context):
    """Gets video previews for videos added to the site by a particular user
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VideoCatalogServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SubmitUploadedVideo': grpc.unary_unary_rpc_method_handler(
          servicer.SubmitUploadedVideo,
          request_deserializer=video__catalog_dot_video__catalog__service__pb2.SubmitUploadedVideoRequest.FromString,
          response_serializer=video__catalog_dot_video__catalog__service__pb2.SubmitUploadedVideoResponse.SerializeToString,
      ),
      'SubmitYouTubeVideo': grpc.unary_unary_rpc_method_handler(
          servicer.SubmitYouTubeVideo,
          request_deserializer=video__catalog_dot_video__catalog__service__pb2.SubmitYouTubeVideoRequest.FromString,
          response_serializer=video__catalog_dot_video__catalog__service__pb2.SubmitYouTubeVideoResponse.SerializeToString,
      ),
      'GetVideo': grpc.unary_unary_rpc_method_handler(
          servicer.GetVideo,
          request_deserializer=video__catalog_dot_video__catalog__service__pb2.GetVideoRequest.FromString,
          response_serializer=video__catalog_dot_video__catalog__service__pb2.GetVideoResponse.SerializeToString,
      ),
      'GetVideoPreviews': grpc.unary_unary_rpc_method_handler(
          servicer.GetVideoPreviews,
          request_deserializer=video__catalog_dot_video__catalog__service__pb2.GetVideoPreviewsRequest.FromString,
          response_serializer=video__catalog_dot_video__catalog__service__pb2.GetVideoPreviewsResponse.SerializeToString,
      ),
      'GetLatestVideoPreviews': grpc.unary_unary_rpc_method_handler(
          servicer.GetLatestVideoPreviews,
          request_deserializer=video__catalog_dot_video__catalog__service__pb2.GetLatestVideoPreviewsRequest.FromString,
          response_serializer=video__catalog_dot_video__catalog__service__pb2.GetLatestVideoPreviewsResponse.SerializeToString,
      ),
      'GetUserVideoPreviews': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserVideoPreviews,
          request_deserializer=video__catalog_dot_video__catalog__service__pb2.GetUserVideoPreviewsRequest.FromString,
          response_serializer=video__catalog_dot_video__catalog__service__pb2.GetUserVideoPreviewsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'killrvideo.video_catalog.VideoCatalogService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
