# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from search import search_service_pb2 as search_dot_search__service__pb2


class SearchServiceStub(object):
  """Searches for videos
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SearchVideos = channel.unary_unary(
        '/killrvideo.search.SearchService/SearchVideos',
        request_serializer=search_dot_search__service__pb2.SearchVideosRequest.SerializeToString,
        response_deserializer=search_dot_search__service__pb2.SearchVideosResponse.FromString,
        )
    self.GetQuerySuggestions = channel.unary_unary(
        '/killrvideo.search.SearchService/GetQuerySuggestions',
        request_serializer=search_dot_search__service__pb2.GetQuerySuggestionsRequest.SerializeToString,
        response_deserializer=search_dot_search__service__pb2.GetQuerySuggestionsResponse.FromString,
        )


class SearchServiceServicer(object):
  """Searches for videos
  """

  def SearchVideos(self, request, context):
    """Searches for videos by a given query term
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetQuerySuggestions(self, request, context):
    """Gets search query suggestions (could be used for typeahead support)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SearchServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SearchVideos': grpc.unary_unary_rpc_method_handler(
          servicer.SearchVideos,
          request_deserializer=search_dot_search__service__pb2.SearchVideosRequest.FromString,
          response_serializer=search_dot_search__service__pb2.SearchVideosResponse.SerializeToString,
      ),
      'GetQuerySuggestions': grpc.unary_unary_rpc_method_handler(
          servicer.GetQuerySuggestions,
          request_deserializer=search_dot_search__service__pb2.GetQuerySuggestionsRequest.FromString,
          response_serializer=search_dot_search__service__pb2.GetQuerySuggestionsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'killrvideo.search.SearchService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
