# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search/search_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from common import common_types_pb2 as common_dot_common__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='search/search_service.proto',
  package='killrvideo.search',
  syntax='proto3',
  serialized_options=_b('\252\002\021KillrVideo.Search'),
  serialized_pb=_b('\n\x1bsearch/search_service.proto\x12\x11killrvideo.search\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19\x63ommon/common_types.proto\"M\n\x13SearchVideosRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x14\n\x0cpaging_state\x18\x10 \x01(\t\"y\n\x14SearchVideosResponse\x12\r\n\x05query\x18\x01 \x01(\t\x12<\n\x06videos\x18\x02 \x03(\x0b\x32,.killrvideo.search.SearchResultsVideoPreview\x12\x14\n\x0cpaging_state\x18\x03 \x01(\t\"\xce\x01\n\x19SearchResultsVideoPreview\x12)\n\x08video_id\x18\x01 \x01(\x0b\x32\x17.killrvideo.common.Uuid\x12.\n\nadded_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x1e\n\x16preview_image_location\x18\x04 \x01(\t\x12(\n\x07user_id\x18\x05 \x01(\x0b\x32\x17.killrvideo.common.Uuid\">\n\x1aGetQuerySuggestionsRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x11\n\tpage_size\x18\x02 \x01(\x05\"A\n\x1bGetQuerySuggestionsResponse\x12\r\n\x05query\x18\x01 \x01(\t\x12\x13\n\x0bsuggestions\x18\x02 \x03(\t2\xe6\x01\n\rSearchService\x12_\n\x0cSearchVideos\x12&.killrvideo.search.SearchVideosRequest\x1a\'.killrvideo.search.SearchVideosResponse\x12t\n\x13GetQuerySuggestions\x12-.killrvideo.search.GetQuerySuggestionsRequest\x1a..killrvideo.search.GetQuerySuggestionsResponseB\x14\xaa\x02\x11KillrVideo.Searchb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,common_dot_common__types__pb2.DESCRIPTOR,])




_SEARCHVIDEOSREQUEST = _descriptor.Descriptor(
  name='SearchVideosRequest',
  full_name='killrvideo.search.SearchVideosRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='killrvideo.search.SearchVideosRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='killrvideo.search.SearchVideosRequest.page_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paging_state', full_name='killrvideo.search.SearchVideosRequest.paging_state', index=2,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=187,
)


_SEARCHVIDEOSRESPONSE = _descriptor.Descriptor(
  name='SearchVideosResponse',
  full_name='killrvideo.search.SearchVideosResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='killrvideo.search.SearchVideosResponse.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='videos', full_name='killrvideo.search.SearchVideosResponse.videos', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paging_state', full_name='killrvideo.search.SearchVideosResponse.paging_state', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=310,
)


_SEARCHRESULTSVIDEOPREVIEW = _descriptor.Descriptor(
  name='SearchResultsVideoPreview',
  full_name='killrvideo.search.SearchResultsVideoPreview',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='video_id', full_name='killrvideo.search.SearchResultsVideoPreview.video_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='added_date', full_name='killrvideo.search.SearchResultsVideoPreview.added_date', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='killrvideo.search.SearchResultsVideoPreview.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preview_image_location', full_name='killrvideo.search.SearchResultsVideoPreview.preview_image_location', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='killrvideo.search.SearchResultsVideoPreview.user_id', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=519,
)


_GETQUERYSUGGESTIONSREQUEST = _descriptor.Descriptor(
  name='GetQuerySuggestionsRequest',
  full_name='killrvideo.search.GetQuerySuggestionsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='killrvideo.search.GetQuerySuggestionsRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='killrvideo.search.GetQuerySuggestionsRequest.page_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=521,
  serialized_end=583,
)


_GETQUERYSUGGESTIONSRESPONSE = _descriptor.Descriptor(
  name='GetQuerySuggestionsResponse',
  full_name='killrvideo.search.GetQuerySuggestionsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='killrvideo.search.GetQuerySuggestionsResponse.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='suggestions', full_name='killrvideo.search.GetQuerySuggestionsResponse.suggestions', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=585,
  serialized_end=650,
)

_SEARCHVIDEOSRESPONSE.fields_by_name['videos'].message_type = _SEARCHRESULTSVIDEOPREVIEW
_SEARCHRESULTSVIDEOPREVIEW.fields_by_name['video_id'].message_type = common_dot_common__types__pb2._UUID
_SEARCHRESULTSVIDEOPREVIEW.fields_by_name['added_date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SEARCHRESULTSVIDEOPREVIEW.fields_by_name['user_id'].message_type = common_dot_common__types__pb2._UUID
DESCRIPTOR.message_types_by_name['SearchVideosRequest'] = _SEARCHVIDEOSREQUEST
DESCRIPTOR.message_types_by_name['SearchVideosResponse'] = _SEARCHVIDEOSRESPONSE
DESCRIPTOR.message_types_by_name['SearchResultsVideoPreview'] = _SEARCHRESULTSVIDEOPREVIEW
DESCRIPTOR.message_types_by_name['GetQuerySuggestionsRequest'] = _GETQUERYSUGGESTIONSREQUEST
DESCRIPTOR.message_types_by_name['GetQuerySuggestionsResponse'] = _GETQUERYSUGGESTIONSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SearchVideosRequest = _reflection.GeneratedProtocolMessageType('SearchVideosRequest', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHVIDEOSREQUEST,
  __module__ = 'search.search_service_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.search.SearchVideosRequest)
  ))
_sym_db.RegisterMessage(SearchVideosRequest)

SearchVideosResponse = _reflection.GeneratedProtocolMessageType('SearchVideosResponse', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHVIDEOSRESPONSE,
  __module__ = 'search.search_service_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.search.SearchVideosResponse)
  ))
_sym_db.RegisterMessage(SearchVideosResponse)

SearchResultsVideoPreview = _reflection.GeneratedProtocolMessageType('SearchResultsVideoPreview', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHRESULTSVIDEOPREVIEW,
  __module__ = 'search.search_service_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.search.SearchResultsVideoPreview)
  ))
_sym_db.RegisterMessage(SearchResultsVideoPreview)

GetQuerySuggestionsRequest = _reflection.GeneratedProtocolMessageType('GetQuerySuggestionsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETQUERYSUGGESTIONSREQUEST,
  __module__ = 'search.search_service_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.search.GetQuerySuggestionsRequest)
  ))
_sym_db.RegisterMessage(GetQuerySuggestionsRequest)

GetQuerySuggestionsResponse = _reflection.GeneratedProtocolMessageType('GetQuerySuggestionsResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETQUERYSUGGESTIONSRESPONSE,
  __module__ = 'search.search_service_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.search.GetQuerySuggestionsResponse)
  ))
_sym_db.RegisterMessage(GetQuerySuggestionsResponse)


DESCRIPTOR._options = None

_SEARCHSERVICE = _descriptor.ServiceDescriptor(
  name='SearchService',
  full_name='killrvideo.search.SearchService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=653,
  serialized_end=883,
  methods=[
  _descriptor.MethodDescriptor(
    name='SearchVideos',
    full_name='killrvideo.search.SearchService.SearchVideos',
    index=0,
    containing_service=None,
    input_type=_SEARCHVIDEOSREQUEST,
    output_type=_SEARCHVIDEOSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetQuerySuggestions',
    full_name='killrvideo.search.SearchService.GetQuerySuggestions',
    index=1,
    containing_service=None,
    input_type=_GETQUERYSUGGESTIONSREQUEST,
    output_type=_GETQUERYSUGGESTIONSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SEARCHSERVICE)

DESCRIPTOR.services_by_name['SearchService'] = _SEARCHSERVICE

# @@protoc_insertion_point(module_scope)
