# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistics/statistics_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import common_types_pb2 as common_dot_common__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='statistics/statistics_service.proto',
  package='killrvideo.statistics',
  syntax='proto3',
  serialized_options=_b('\252\002\025KillrVideo.Statistics'),
  serialized_pb=_b('\n#statistics/statistics_service.proto\x12\x15killrvideo.statistics\x1a\x19\x63ommon/common_types.proto\"I\n\x1cRecordPlaybackStartedRequest\x12)\n\x08video_id\x18\x01 \x01(\x0b\x32\x17.killrvideo.common.Uuid\"\x1f\n\x1dRecordPlaybackStartedResponse\"E\n\x17GetNumberOfPlaysRequest\x12*\n\tvideo_ids\x18\x01 \x03(\x0b\x32\x17.killrvideo.common.Uuid\"K\n\x18GetNumberOfPlaysResponse\x12/\n\x05stats\x18\x01 \x03(\x0b\x32 .killrvideo.statistics.PlayStats\"E\n\tPlayStats\x12)\n\x08video_id\x18\x01 \x01(\x0b\x32\x17.killrvideo.common.Uuid\x12\r\n\x05views\x18\x02 \x01(\x03\x32\x8d\x02\n\x11StatisticsService\x12\x82\x01\n\x15RecordPlaybackStarted\x12\x33.killrvideo.statistics.RecordPlaybackStartedRequest\x1a\x34.killrvideo.statistics.RecordPlaybackStartedResponse\x12s\n\x10GetNumberOfPlays\x12..killrvideo.statistics.GetNumberOfPlaysRequest\x1a/.killrvideo.statistics.GetNumberOfPlaysResponseB\x18\xaa\x02\x15KillrVideo.Statisticsb\x06proto3')
  ,
  dependencies=[common_dot_common__types__pb2.DESCRIPTOR,])




_RECORDPLAYBACKSTARTEDREQUEST = _descriptor.Descriptor(
  name='RecordPlaybackStartedRequest',
  full_name='killrvideo.statistics.RecordPlaybackStartedRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='video_id', full_name='killrvideo.statistics.RecordPlaybackStartedRequest.video_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=162,
)


_RECORDPLAYBACKSTARTEDRESPONSE = _descriptor.Descriptor(
  name='RecordPlaybackStartedResponse',
  full_name='killrvideo.statistics.RecordPlaybackStartedResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=195,
)


_GETNUMBEROFPLAYSREQUEST = _descriptor.Descriptor(
  name='GetNumberOfPlaysRequest',
  full_name='killrvideo.statistics.GetNumberOfPlaysRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='video_ids', full_name='killrvideo.statistics.GetNumberOfPlaysRequest.video_ids', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=266,
)


_GETNUMBEROFPLAYSRESPONSE = _descriptor.Descriptor(
  name='GetNumberOfPlaysResponse',
  full_name='killrvideo.statistics.GetNumberOfPlaysResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stats', full_name='killrvideo.statistics.GetNumberOfPlaysResponse.stats', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=343,
)


_PLAYSTATS = _descriptor.Descriptor(
  name='PlayStats',
  full_name='killrvideo.statistics.PlayStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='video_id', full_name='killrvideo.statistics.PlayStats.video_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='views', full_name='killrvideo.statistics.PlayStats.views', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=414,
)

_RECORDPLAYBACKSTARTEDREQUEST.fields_by_name['video_id'].message_type = common_dot_common__types__pb2._UUID
_GETNUMBEROFPLAYSREQUEST.fields_by_name['video_ids'].message_type = common_dot_common__types__pb2._UUID
_GETNUMBEROFPLAYSRESPONSE.fields_by_name['stats'].message_type = _PLAYSTATS
_PLAYSTATS.fields_by_name['video_id'].message_type = common_dot_common__types__pb2._UUID
DESCRIPTOR.message_types_by_name['RecordPlaybackStartedRequest'] = _RECORDPLAYBACKSTARTEDREQUEST
DESCRIPTOR.message_types_by_name['RecordPlaybackStartedResponse'] = _RECORDPLAYBACKSTARTEDRESPONSE
DESCRIPTOR.message_types_by_name['GetNumberOfPlaysRequest'] = _GETNUMBEROFPLAYSREQUEST
DESCRIPTOR.message_types_by_name['GetNumberOfPlaysResponse'] = _GETNUMBEROFPLAYSRESPONSE
DESCRIPTOR.message_types_by_name['PlayStats'] = _PLAYSTATS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecordPlaybackStartedRequest = _reflection.GeneratedProtocolMessageType('RecordPlaybackStartedRequest', (_message.Message,), dict(
  DESCRIPTOR = _RECORDPLAYBACKSTARTEDREQUEST,
  __module__ = 'statistics.statistics_service_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.statistics.RecordPlaybackStartedRequest)
  ))
_sym_db.RegisterMessage(RecordPlaybackStartedRequest)

RecordPlaybackStartedResponse = _reflection.GeneratedProtocolMessageType('RecordPlaybackStartedResponse', (_message.Message,), dict(
  DESCRIPTOR = _RECORDPLAYBACKSTARTEDRESPONSE,
  __module__ = 'statistics.statistics_service_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.statistics.RecordPlaybackStartedResponse)
  ))
_sym_db.RegisterMessage(RecordPlaybackStartedResponse)

GetNumberOfPlaysRequest = _reflection.GeneratedProtocolMessageType('GetNumberOfPlaysRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETNUMBEROFPLAYSREQUEST,
  __module__ = 'statistics.statistics_service_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.statistics.GetNumberOfPlaysRequest)
  ))
_sym_db.RegisterMessage(GetNumberOfPlaysRequest)

GetNumberOfPlaysResponse = _reflection.GeneratedProtocolMessageType('GetNumberOfPlaysResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETNUMBEROFPLAYSRESPONSE,
  __module__ = 'statistics.statistics_service_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.statistics.GetNumberOfPlaysResponse)
  ))
_sym_db.RegisterMessage(GetNumberOfPlaysResponse)

PlayStats = _reflection.GeneratedProtocolMessageType('PlayStats', (_message.Message,), dict(
  DESCRIPTOR = _PLAYSTATS,
  __module__ = 'statistics.statistics_service_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.statistics.PlayStats)
  ))
_sym_db.RegisterMessage(PlayStats)


DESCRIPTOR._options = None

_STATISTICSSERVICE = _descriptor.ServiceDescriptor(
  name='StatisticsService',
  full_name='killrvideo.statistics.StatisticsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=417,
  serialized_end=686,
  methods=[
  _descriptor.MethodDescriptor(
    name='RecordPlaybackStarted',
    full_name='killrvideo.statistics.StatisticsService.RecordPlaybackStarted',
    index=0,
    containing_service=None,
    input_type=_RECORDPLAYBACKSTARTEDREQUEST,
    output_type=_RECORDPLAYBACKSTARTEDRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetNumberOfPlays',
    full_name='killrvideo.statistics.StatisticsService.GetNumberOfPlays',
    index=1,
    containing_service=None,
    input_type=_GETNUMBEROFPLAYSREQUEST,
    output_type=_GETNUMBEROFPLAYSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STATISTICSSERVICE)

DESCRIPTOR.services_by_name['StatisticsService'] = _STATISTICSSERVICE

# @@protoc_insertion_point(module_scope)
