# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from user_management import user_management_service_pb2 as user__management_dot_user__management__service__pb2


class UserManagementServiceStub(object):
  """The service responsible for managing user information
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateUser = channel.unary_unary(
        '/killrvideo.user_management.UserManagementService/CreateUser',
        request_serializer=user__management_dot_user__management__service__pb2.CreateUserRequest.SerializeToString,
        response_deserializer=user__management_dot_user__management__service__pb2.CreateUserResponse.FromString,
        )
    self.VerifyCredentials = channel.unary_unary(
        '/killrvideo.user_management.UserManagementService/VerifyCredentials',
        request_serializer=user__management_dot_user__management__service__pb2.VerifyCredentialsRequest.SerializeToString,
        response_deserializer=user__management_dot_user__management__service__pb2.VerifyCredentialsResponse.FromString,
        )
    self.GetUserProfile = channel.unary_unary(
        '/killrvideo.user_management.UserManagementService/GetUserProfile',
        request_serializer=user__management_dot_user__management__service__pb2.GetUserProfileRequest.SerializeToString,
        response_deserializer=user__management_dot_user__management__service__pb2.GetUserProfileResponse.FromString,
        )


class UserManagementServiceServicer(object):
  """The service responsible for managing user information
  """

  def CreateUser(self, request, context):
    """Creates a new user
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VerifyCredentials(self, request, context):
    """Verify a user's username and password
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserProfile(self, request, context):
    """Gets a user or group of user's profiles
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserManagementServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateUser': grpc.unary_unary_rpc_method_handler(
          servicer.CreateUser,
          request_deserializer=user__management_dot_user__management__service__pb2.CreateUserRequest.FromString,
          response_serializer=user__management_dot_user__management__service__pb2.CreateUserResponse.SerializeToString,
      ),
      'VerifyCredentials': grpc.unary_unary_rpc_method_handler(
          servicer.VerifyCredentials,
          request_deserializer=user__management_dot_user__management__service__pb2.VerifyCredentialsRequest.FromString,
          response_serializer=user__management_dot_user__management__service__pb2.VerifyCredentialsResponse.SerializeToString,
      ),
      'GetUserProfile': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserProfile,
          request_deserializer=user__management_dot_user__management__service__pb2.GetUserProfileRequest.FromString,
          response_serializer=user__management_dot_user__management__service__pb2.GetUserProfileResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'killrvideo.user_management.UserManagementService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
