# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user-management/user_management_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import common_types_pb2 as common_dot_common__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='user-management/user_management_service.proto',
  package='killrvideo.user_management',
  syntax='proto3',
  serialized_options=_b('\252\002\031KillrVideo.UserManagement'),
  serialized_pb=_b('\n-user-management/user_management_service.proto\x12\x1akillrvideo.user_management\x1a\x19\x63ommon/common_types.proto\"\x85\x01\n\x11\x43reateUserRequest\x12(\n\x07user_id\x18\x01 \x01(\x0b\x32\x17.killrvideo.common.Uuid\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t\"\x14\n\x12\x43reateUserResponse\";\n\x18VerifyCredentialsRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"E\n\x19VerifyCredentialsResponse\x12(\n\x07user_id\x18\x01 \x01(\x0b\x32\x17.killrvideo.common.Uuid\"B\n\x15GetUserProfileRequest\x12)\n\x08user_ids\x18\x01 \x03(\x0b\x32\x17.killrvideo.common.Uuid\"S\n\x16GetUserProfileResponse\x12\x39\n\x08profiles\x18\x01 \x03(\x0b\x32\'.killrvideo.user_management.UserProfile\"m\n\x0bUserProfile\x12(\n\x07user_id\x18\x01 \x01(\x0b\x32\x17.killrvideo.common.Uuid\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t2\x80\x03\n\x15UserManagementService\x12k\n\nCreateUser\x12-.killrvideo.user_management.CreateUserRequest\x1a..killrvideo.user_management.CreateUserResponse\x12\x80\x01\n\x11VerifyCredentials\x12\x34.killrvideo.user_management.VerifyCredentialsRequest\x1a\x35.killrvideo.user_management.VerifyCredentialsResponse\x12w\n\x0eGetUserProfile\x12\x31.killrvideo.user_management.GetUserProfileRequest\x1a\x32.killrvideo.user_management.GetUserProfileResponseB\x1c\xaa\x02\x19KillrVideo.UserManagementb\x06proto3')
  ,
  dependencies=[common_dot_common__types__pb2.DESCRIPTOR,])




_CREATEUSERREQUEST = _descriptor.Descriptor(
  name='CreateUserRequest',
  full_name='killrvideo.user_management.CreateUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='killrvideo.user_management.CreateUserRequest.user_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='killrvideo.user_management.CreateUserRequest.first_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='killrvideo.user_management.CreateUserRequest.last_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='killrvideo.user_management.CreateUserRequest.email', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='killrvideo.user_management.CreateUserRequest.password', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=238,
)


_CREATEUSERRESPONSE = _descriptor.Descriptor(
  name='CreateUserResponse',
  full_name='killrvideo.user_management.CreateUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=260,
)


_VERIFYCREDENTIALSREQUEST = _descriptor.Descriptor(
  name='VerifyCredentialsRequest',
  full_name='killrvideo.user_management.VerifyCredentialsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='killrvideo.user_management.VerifyCredentialsRequest.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='killrvideo.user_management.VerifyCredentialsRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=321,
)


_VERIFYCREDENTIALSRESPONSE = _descriptor.Descriptor(
  name='VerifyCredentialsResponse',
  full_name='killrvideo.user_management.VerifyCredentialsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='killrvideo.user_management.VerifyCredentialsResponse.user_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=392,
)


_GETUSERPROFILEREQUEST = _descriptor.Descriptor(
  name='GetUserProfileRequest',
  full_name='killrvideo.user_management.GetUserProfileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_ids', full_name='killrvideo.user_management.GetUserProfileRequest.user_ids', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=460,
)


_GETUSERPROFILERESPONSE = _descriptor.Descriptor(
  name='GetUserProfileResponse',
  full_name='killrvideo.user_management.GetUserProfileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='profiles', full_name='killrvideo.user_management.GetUserProfileResponse.profiles', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=462,
  serialized_end=545,
)


_USERPROFILE = _descriptor.Descriptor(
  name='UserProfile',
  full_name='killrvideo.user_management.UserProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='killrvideo.user_management.UserProfile.user_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='killrvideo.user_management.UserProfile.first_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='killrvideo.user_management.UserProfile.last_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='killrvideo.user_management.UserProfile.email', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=547,
  serialized_end=656,
)

_CREATEUSERREQUEST.fields_by_name['user_id'].message_type = common_dot_common__types__pb2._UUID
_VERIFYCREDENTIALSRESPONSE.fields_by_name['user_id'].message_type = common_dot_common__types__pb2._UUID
_GETUSERPROFILEREQUEST.fields_by_name['user_ids'].message_type = common_dot_common__types__pb2._UUID
_GETUSERPROFILERESPONSE.fields_by_name['profiles'].message_type = _USERPROFILE
_USERPROFILE.fields_by_name['user_id'].message_type = common_dot_common__types__pb2._UUID
DESCRIPTOR.message_types_by_name['CreateUserRequest'] = _CREATEUSERREQUEST
DESCRIPTOR.message_types_by_name['CreateUserResponse'] = _CREATEUSERRESPONSE
DESCRIPTOR.message_types_by_name['VerifyCredentialsRequest'] = _VERIFYCREDENTIALSREQUEST
DESCRIPTOR.message_types_by_name['VerifyCredentialsResponse'] = _VERIFYCREDENTIALSRESPONSE
DESCRIPTOR.message_types_by_name['GetUserProfileRequest'] = _GETUSERPROFILEREQUEST
DESCRIPTOR.message_types_by_name['GetUserProfileResponse'] = _GETUSERPROFILERESPONSE
DESCRIPTOR.message_types_by_name['UserProfile'] = _USERPROFILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateUserRequest = _reflection.GeneratedProtocolMessageType('CreateUserRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEUSERREQUEST,
  __module__ = 'user_management.user_management_service_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.user_management.CreateUserRequest)
  ))
_sym_db.RegisterMessage(CreateUserRequest)

CreateUserResponse = _reflection.GeneratedProtocolMessageType('CreateUserResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATEUSERRESPONSE,
  __module__ = 'user_management.user_management_service_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.user_management.CreateUserResponse)
  ))
_sym_db.RegisterMessage(CreateUserResponse)

VerifyCredentialsRequest = _reflection.GeneratedProtocolMessageType('VerifyCredentialsRequest', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYCREDENTIALSREQUEST,
  __module__ = 'user_management.user_management_service_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.user_management.VerifyCredentialsRequest)
  ))
_sym_db.RegisterMessage(VerifyCredentialsRequest)

VerifyCredentialsResponse = _reflection.GeneratedProtocolMessageType('VerifyCredentialsResponse', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYCREDENTIALSRESPONSE,
  __module__ = 'user_management.user_management_service_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.user_management.VerifyCredentialsResponse)
  ))
_sym_db.RegisterMessage(VerifyCredentialsResponse)

GetUserProfileRequest = _reflection.GeneratedProtocolMessageType('GetUserProfileRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETUSERPROFILEREQUEST,
  __module__ = 'user_management.user_management_service_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.user_management.GetUserProfileRequest)
  ))
_sym_db.RegisterMessage(GetUserProfileRequest)

GetUserProfileResponse = _reflection.GeneratedProtocolMessageType('GetUserProfileResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETUSERPROFILERESPONSE,
  __module__ = 'user_management.user_management_service_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.user_management.GetUserProfileResponse)
  ))
_sym_db.RegisterMessage(GetUserProfileResponse)

UserProfile = _reflection.GeneratedProtocolMessageType('UserProfile', (_message.Message,), dict(
  DESCRIPTOR = _USERPROFILE,
  __module__ = 'user_management.user_management_service_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.user_management.UserProfile)
  ))
_sym_db.RegisterMessage(UserProfile)


DESCRIPTOR._options = None

_USERMANAGEMENTSERVICE = _descriptor.ServiceDescriptor(
  name='UserManagementService',
  full_name='killrvideo.user_management.UserManagementService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=659,
  serialized_end=1043,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateUser',
    full_name='killrvideo.user_management.UserManagementService.CreateUser',
    index=0,
    containing_service=None,
    input_type=_CREATEUSERREQUEST,
    output_type=_CREATEUSERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='VerifyCredentials',
    full_name='killrvideo.user_management.UserManagementService.VerifyCredentials',
    index=1,
    containing_service=None,
    input_type=_VERIFYCREDENTIALSREQUEST,
    output_type=_VERIFYCREDENTIALSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetUserProfile',
    full_name='killrvideo.user_management.UserManagementService.GetUserProfile',
    index=2,
    containing_service=None,
    input_type=_GETUSERPROFILEREQUEST,
    output_type=_GETUSERPROFILERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERMANAGEMENTSERVICE)

DESCRIPTOR.services_by_name['UserManagementService'] = _USERMANAGEMENTSERVICE

# @@protoc_insertion_point(module_scope)
