# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ratings/ratings_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import common_types_pb2 as common_dot_common__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ratings/ratings_service.proto',
  package='killrvideo.ratings',
  syntax='proto3',
  serialized_options=_b('\252\002\022KillrVideo.Ratings'),
  serialized_pb=_b('\n\x1dratings/ratings_service.proto\x12\x12killrvideo.ratings\x1a\x19\x63ommon/common_types.proto\"w\n\x10RateVideoRequest\x12)\n\x08video_id\x18\x01 \x01(\x0b\x32\x17.killrvideo.common.Uuid\x12(\n\x07user_id\x18\x02 \x01(\x0b\x32\x17.killrvideo.common.Uuid\x12\x0e\n\x06rating\x18\x03 \x01(\x05\"\x13\n\x11RateVideoResponse\"=\n\x10GetRatingRequest\x12)\n\x08video_id\x18\x01 \x01(\x0b\x32\x17.killrvideo.common.Uuid\"l\n\x11GetRatingResponse\x12)\n\x08video_id\x18\x01 \x01(\x0b\x32\x17.killrvideo.common.Uuid\x12\x15\n\rratings_count\x18\x02 \x01(\x03\x12\x15\n\rratings_total\x18\x03 \x01(\x03\"k\n\x14GetUserRatingRequest\x12)\n\x08video_id\x18\x01 \x01(\x0b\x32\x17.killrvideo.common.Uuid\x12(\n\x07user_id\x18\x02 \x01(\x0b\x32\x17.killrvideo.common.Uuid\"|\n\x15GetUserRatingResponse\x12)\n\x08video_id\x18\x01 \x01(\x0b\x32\x17.killrvideo.common.Uuid\x12(\n\x07user_id\x18\x02 \x01(\x0b\x32\x17.killrvideo.common.Uuid\x12\x0e\n\x06rating\x18\x03 \x01(\x05\x32\xaa\x02\n\x0eRatingsService\x12X\n\tRateVideo\x12$.killrvideo.ratings.RateVideoRequest\x1a%.killrvideo.ratings.RateVideoResponse\x12X\n\tGetRating\x12$.killrvideo.ratings.GetRatingRequest\x1a%.killrvideo.ratings.GetRatingResponse\x12\x64\n\rGetUserRating\x12(.killrvideo.ratings.GetUserRatingRequest\x1a).killrvideo.ratings.GetUserRatingResponseB\x15\xaa\x02\x12KillrVideo.Ratingsb\x06proto3')
  ,
  dependencies=[common_dot_common__types__pb2.DESCRIPTOR,])




_RATEVIDEOREQUEST = _descriptor.Descriptor(
  name='RateVideoRequest',
  full_name='killrvideo.ratings.RateVideoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='video_id', full_name='killrvideo.ratings.RateVideoRequest.video_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='killrvideo.ratings.RateVideoRequest.user_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rating', full_name='killrvideo.ratings.RateVideoRequest.rating', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=199,
)


_RATEVIDEORESPONSE = _descriptor.Descriptor(
  name='RateVideoResponse',
  full_name='killrvideo.ratings.RateVideoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=220,
)


_GETRATINGREQUEST = _descriptor.Descriptor(
  name='GetRatingRequest',
  full_name='killrvideo.ratings.GetRatingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='video_id', full_name='killrvideo.ratings.GetRatingRequest.video_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=283,
)


_GETRATINGRESPONSE = _descriptor.Descriptor(
  name='GetRatingResponse',
  full_name='killrvideo.ratings.GetRatingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='video_id', full_name='killrvideo.ratings.GetRatingResponse.video_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ratings_count', full_name='killrvideo.ratings.GetRatingResponse.ratings_count', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ratings_total', full_name='killrvideo.ratings.GetRatingResponse.ratings_total', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=393,
)


_GETUSERRATINGREQUEST = _descriptor.Descriptor(
  name='GetUserRatingRequest',
  full_name='killrvideo.ratings.GetUserRatingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='video_id', full_name='killrvideo.ratings.GetUserRatingRequest.video_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='killrvideo.ratings.GetUserRatingRequest.user_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=502,
)


_GETUSERRATINGRESPONSE = _descriptor.Descriptor(
  name='GetUserRatingResponse',
  full_name='killrvideo.ratings.GetUserRatingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='video_id', full_name='killrvideo.ratings.GetUserRatingResponse.video_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='killrvideo.ratings.GetUserRatingResponse.user_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rating', full_name='killrvideo.ratings.GetUserRatingResponse.rating', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=504,
  serialized_end=628,
)

_RATEVIDEOREQUEST.fields_by_name['video_id'].message_type = common_dot_common__types__pb2._UUID
_RATEVIDEOREQUEST.fields_by_name['user_id'].message_type = common_dot_common__types__pb2._UUID
_GETRATINGREQUEST.fields_by_name['video_id'].message_type = common_dot_common__types__pb2._UUID
_GETRATINGRESPONSE.fields_by_name['video_id'].message_type = common_dot_common__types__pb2._UUID
_GETUSERRATINGREQUEST.fields_by_name['video_id'].message_type = common_dot_common__types__pb2._UUID
_GETUSERRATINGREQUEST.fields_by_name['user_id'].message_type = common_dot_common__types__pb2._UUID
_GETUSERRATINGRESPONSE.fields_by_name['video_id'].message_type = common_dot_common__types__pb2._UUID
_GETUSERRATINGRESPONSE.fields_by_name['user_id'].message_type = common_dot_common__types__pb2._UUID
DESCRIPTOR.message_types_by_name['RateVideoRequest'] = _RATEVIDEOREQUEST
DESCRIPTOR.message_types_by_name['RateVideoResponse'] = _RATEVIDEORESPONSE
DESCRIPTOR.message_types_by_name['GetRatingRequest'] = _GETRATINGREQUEST
DESCRIPTOR.message_types_by_name['GetRatingResponse'] = _GETRATINGRESPONSE
DESCRIPTOR.message_types_by_name['GetUserRatingRequest'] = _GETUSERRATINGREQUEST
DESCRIPTOR.message_types_by_name['GetUserRatingResponse'] = _GETUSERRATINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RateVideoRequest = _reflection.GeneratedProtocolMessageType('RateVideoRequest', (_message.Message,), dict(
  DESCRIPTOR = _RATEVIDEOREQUEST,
  __module__ = 'ratings.ratings_service_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.ratings.RateVideoRequest)
  ))
_sym_db.RegisterMessage(RateVideoRequest)

RateVideoResponse = _reflection.GeneratedProtocolMessageType('RateVideoResponse', (_message.Message,), dict(
  DESCRIPTOR = _RATEVIDEORESPONSE,
  __module__ = 'ratings.ratings_service_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.ratings.RateVideoResponse)
  ))
_sym_db.RegisterMessage(RateVideoResponse)

GetRatingRequest = _reflection.GeneratedProtocolMessageType('GetRatingRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETRATINGREQUEST,
  __module__ = 'ratings.ratings_service_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.ratings.GetRatingRequest)
  ))
_sym_db.RegisterMessage(GetRatingRequest)

GetRatingResponse = _reflection.GeneratedProtocolMessageType('GetRatingResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETRATINGRESPONSE,
  __module__ = 'ratings.ratings_service_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.ratings.GetRatingResponse)
  ))
_sym_db.RegisterMessage(GetRatingResponse)

GetUserRatingRequest = _reflection.GeneratedProtocolMessageType('GetUserRatingRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETUSERRATINGREQUEST,
  __module__ = 'ratings.ratings_service_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.ratings.GetUserRatingRequest)
  ))
_sym_db.RegisterMessage(GetUserRatingRequest)

GetUserRatingResponse = _reflection.GeneratedProtocolMessageType('GetUserRatingResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETUSERRATINGRESPONSE,
  __module__ = 'ratings.ratings_service_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.ratings.GetUserRatingResponse)
  ))
_sym_db.RegisterMessage(GetUserRatingResponse)


DESCRIPTOR._options = None

_RATINGSSERVICE = _descriptor.ServiceDescriptor(
  name='RatingsService',
  full_name='killrvideo.ratings.RatingsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=631,
  serialized_end=929,
  methods=[
  _descriptor.MethodDescriptor(
    name='RateVideo',
    full_name='killrvideo.ratings.RatingsService.RateVideo',
    index=0,
    containing_service=None,
    input_type=_RATEVIDEOREQUEST,
    output_type=_RATEVIDEORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetRating',
    full_name='killrvideo.ratings.RatingsService.GetRating',
    index=1,
    containing_service=None,
    input_type=_GETRATINGREQUEST,
    output_type=_GETRATINGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetUserRating',
    full_name='killrvideo.ratings.RatingsService.GetUserRating',
    index=2,
    containing_service=None,
    input_type=_GETUSERRATINGREQUEST,
    output_type=_GETUSERRATINGRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RATINGSSERVICE)

DESCRIPTOR.services_by_name['RatingsService'] = _RATINGSSERVICE

# @@protoc_insertion_point(module_scope)
