# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ratings/ratings_events.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import common_types_pb2 as common_dot_common__types__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ratings/ratings_events.proto',
  package='killrvideo.ratings.events',
  syntax='proto3',
  serialized_options=_b('\252\002\031KillrVideo.Ratings.Events'),
  serialized_pb=_b('\n\x1cratings/ratings_events.proto\x12\x19killrvideo.ratings.events\x1a\x19\x63ommon/common_types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x01\n\x0eUserRatedVideo\x12)\n\x08video_id\x18\x01 \x01(\x0b\x32\x17.killrvideo.common.Uuid\x12(\n\x07user_id\x18\x02 \x01(\x0b\x32\x17.killrvideo.common.Uuid\x12\x0e\n\x06rating\x18\x03 \x01(\x05\x12\x34\n\x10rating_timestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x1c\xaa\x02\x19KillrVideo.Ratings.Eventsb\x06proto3')
  ,
  dependencies=[common_dot_common__types__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_USERRATEDVIDEO = _descriptor.Descriptor(
  name='UserRatedVideo',
  full_name='killrvideo.ratings.events.UserRatedVideo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='video_id', full_name='killrvideo.ratings.events.UserRatedVideo.video_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='killrvideo.ratings.events.UserRatedVideo.user_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rating', full_name='killrvideo.ratings.events.UserRatedVideo.rating', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rating_timestamp', full_name='killrvideo.ratings.events.UserRatedVideo.rating_timestamp', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=291,
)

_USERRATEDVIDEO.fields_by_name['video_id'].message_type = common_dot_common__types__pb2._UUID
_USERRATEDVIDEO.fields_by_name['user_id'].message_type = common_dot_common__types__pb2._UUID
_USERRATEDVIDEO.fields_by_name['rating_timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['UserRatedVideo'] = _USERRATEDVIDEO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserRatedVideo = _reflection.GeneratedProtocolMessageType('UserRatedVideo', (_message.Message,), dict(
  DESCRIPTOR = _USERRATEDVIDEO,
  __module__ = 'ratings.ratings_events_pb2'
  # @@protoc_insertion_point(class_scope:killrvideo.ratings.events.UserRatedVideo)
  ))
_sym_db.RegisterMessage(UserRatedVideo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
