# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from ratings import ratings_service_pb2 as ratings_dot_ratings__service__pb2


class RatingsServiceStub(object):
  """Service that manages user's ratings of videos
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RateVideo = channel.unary_unary(
        '/killrvideo.ratings.RatingsService/RateVideo',
        request_serializer=ratings_dot_ratings__service__pb2.RateVideoRequest.SerializeToString,
        response_deserializer=ratings_dot_ratings__service__pb2.RateVideoResponse.FromString,
        )
    self.GetRating = channel.unary_unary(
        '/killrvideo.ratings.RatingsService/GetRating',
        request_serializer=ratings_dot_ratings__service__pb2.GetRatingRequest.SerializeToString,
        response_deserializer=ratings_dot_ratings__service__pb2.GetRatingResponse.FromString,
        )
    self.GetUserRating = channel.unary_unary(
        '/killrvideo.ratings.RatingsService/GetUserRating',
        request_serializer=ratings_dot_ratings__service__pb2.GetUserRatingRequest.SerializeToString,
        response_deserializer=ratings_dot_ratings__service__pb2.GetUserRatingResponse.FromString,
        )


class RatingsServiceServicer(object):
  """Service that manages user's ratings of videos
  """

  def RateVideo(self, request, context):
    """Rate a video
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRating(self, request, context):
    """Gets the current rating stats for a video
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserRating(self, request, context):
    """Gets a user's rating of a specific video and returns 0 if the user hasn't rated the video
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RatingsServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RateVideo': grpc.unary_unary_rpc_method_handler(
          servicer.RateVideo,
          request_deserializer=ratings_dot_ratings__service__pb2.RateVideoRequest.FromString,
          response_serializer=ratings_dot_ratings__service__pb2.RateVideoResponse.SerializeToString,
      ),
      'GetRating': grpc.unary_unary_rpc_method_handler(
          servicer.GetRating,
          request_deserializer=ratings_dot_ratings__service__pb2.GetRatingRequest.FromString,
          response_serializer=ratings_dot_ratings__service__pb2.GetRatingResponse.SerializeToString,
      ),
      'GetUserRating': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserRating,
          request_deserializer=ratings_dot_ratings__service__pb2.GetUserRatingRequest.FromString,
          response_serializer=ratings_dot_ratings__service__pb2.GetUserRatingResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'killrvideo.ratings.RatingsService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
