# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from suggested_videos import suggested_videos_service_pb2 as suggested__videos_dot_suggested__videos__service__pb2


class SuggestedVideoServiceStub(object):
  """Service responsible for generating video suggestions
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetRelatedVideos = channel.unary_unary(
        '/killrvideo.suggested_videos.SuggestedVideoService/GetRelatedVideos',
        request_serializer=suggested__videos_dot_suggested__videos__service__pb2.GetRelatedVideosRequest.SerializeToString,
        response_deserializer=suggested__videos_dot_suggested__videos__service__pb2.GetRelatedVideosResponse.FromString,
        )
    self.GetSuggestedForUser = channel.unary_unary(
        '/killrvideo.suggested_videos.SuggestedVideoService/GetSuggestedForUser',
        request_serializer=suggested__videos_dot_suggested__videos__service__pb2.GetSuggestedForUserRequest.SerializeToString,
        response_deserializer=suggested__videos_dot_suggested__videos__service__pb2.GetSuggestedForUserResponse.FromString,
        )


class SuggestedVideoServiceServicer(object):
  """Service responsible for generating video suggestions
  """

  def GetRelatedVideos(self, request, context):
    """Gets videos related to another video
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSuggestedForUser(self, request, context):
    """Gets personalized video suggestions for a user
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SuggestedVideoServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetRelatedVideos': grpc.unary_unary_rpc_method_handler(
          servicer.GetRelatedVideos,
          request_deserializer=suggested__videos_dot_suggested__videos__service__pb2.GetRelatedVideosRequest.FromString,
          response_serializer=suggested__videos_dot_suggested__videos__service__pb2.GetRelatedVideosResponse.SerializeToString,
      ),
      'GetSuggestedForUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetSuggestedForUser,
          request_deserializer=suggested__videos_dot_suggested__videos__service__pb2.GetSuggestedForUserRequest.FromString,
          response_serializer=suggested__videos_dot_suggested__videos__service__pb2.GetSuggestedForUserResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'killrvideo.suggested_videos.SuggestedVideoService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
